### PR TITLE
Win recipes

### PR DESCRIPTION
**Pull request by patgmac**

### CODE REVIEW

**Comment by gregneagle** [comment]
Assuming you will be accepting your own pull request...

**Comment by patgmac** [comment]
Yea, was moving a branch into master. There was probably a better way to git this.

**Comment by jfuchtm** [comment]
Is this as easy as your recipe makes it look?

**Comment by patgmac** [comment]
Which part? Windows recipes? It's fairly easy if there is a parent recipe to borrow from. There are some dependencies that need to be install for the Windows stuff and I need to document that soon.

**Comment by jfuchtm** [comment]
I was just about to ask you that.  Getting an error on your 32bit Google, Unknown processor 'BESRelevanceProvider'  I need to learn this code.  What a time saver this would be for LANrev and our Windows users.

**Comment by patgmac** [comment]
I'll try to document this very soon.

**Comment by jfuchtm** [comment]
Thanks

**Comment by jfuchtm** [comment]
Can I ask a favor?  Can you look at com.github.autopkg.gregneagle-recipes, the FirefoxAutoconfig.pkg.recipe.  Can this be easily altered to port to LANrev?  Like I say I am just starting to get into the code and this is the only one we currently have to package to distribute.  Yes, I owe you a beer or two.  We need to meet up to discuss the payoff.
Thanks

**Comment by gregneagle** [comment]
The FirefoxAutoconfig.pkg.recipe creates an Apple package. You should be able to create a child recipe that imports the package into your LANrev repo -- it would be nearly identical to any recipe that imports pkgs into LANrev.

If you are asking if the FirefoxAutoconfig.pkg.recipe can be ported to make Windows pkgs, that is a very tall order, and not trivial at all. It would not be a "port" so much as a band-new recipe using lots of new processors.

**Comment by jfuchtm** [comment]
You were right on the first comment, I just want to bounce it into a LANrev package.  I will look further into making a child recipe that does this.

Thanks

**Comment by patgmac** [comment]
@jfuchtm I added a FirefoxAutoconfig LANrev recipe to my repo. Give it a try. @gregneagle Hope you don't mind, I heavily borrowed your description since it all applies to my recipe as well.

**Comment by jfuchtm** [comment]
I will give it a try, AutoPkg only, not AUtoPkgr?

**Comment by patgmac** [comment]
AutoPkgR is a GUI for AutoPkg.

**Comment by jfuchtm** [comment]
Right, but as in the Chrome 64 bit you made it will only run in AutoPkg, not AutoPkgr

**Comment by patgmac** [comment]
There is no way (that I am aware) to make a AutoPkgr version of a recipe. The Chrome-Win recipes are getting an error in AutoPkgr (and usually autopkg) because of a process in the parent recipe (related to 7z). I have no control over that parent recipe. Regardless, the FirefoxAutoconfig recipe is a Mac recipe, so doesn't need 7z.

**Comment by jfuchtm** [comment]
Great work Pat.  The Firefox for Windows and the LANrev Firefox Autoconfig for Mac both work great. 

-Jeff

**Pull request merged**
